server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true

spring:
  application:
    name: spring-seed
  profiles.active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    default-property-inclusion: non_empty

mybatis:
  type-aliases-package: com.yodinfo.seed.domain
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*.xml

mapper:
  mappers: com.yodinfo.seed.dao.BasicMapper, com.yodinfo.seed.dao.CommonMapper
  not-empty: true
  identity: postgresql
  use-simple-type: false

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    com.yodinfo.seed.dao: DEBUG

jasypt:
  encryptor:
    password: Bda7bXaExAA
    property:
      prefix: "Yod@["
      suffix: "]"

---
spring:
  profiles: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbc-url: jdbc:postgresql://47.99.143.50:5432/kai
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: Yod@[LufBN5drtvdSfQFUDy5v8ANvGQ4sPN6z]

logging:
  level:
    root: INFO

---
spring:
  profiles: prod