spring:
  shardingsphere:
    datasource:
      names:
        master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://106.12.99.31:3306/iakuil?characterEncoding=utf-8
        username: root
        password: Yod@[jXy3aYdJbFf8rkj4HWUG+FZ41gh6/WmN]
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://119.45.239.30:3306/iakuil?characterEncoding=utf-8
        username: root
        password: Yod@[jXy3aYdJbFf8rkj4HWUG+FZ41gh6/WmN]
    masterslave:
      load-balance-algorithm-type: round_robin
      name: dataSource
      master-data-source-name: master
      slave-data-source-names: slave
    props:
      sql:
        show: true
  redis:
    host: redis.iakuil.com
    port: 6379
    password: Yod@[ypgh62docYY/PPcZ0v16lGMDdKDTNSxq]
    lettuce:
      pool:
        max-active: 10
        max-wait: 5000ms
        max-idle: 10
        min-idle: 0
      timeout: 10000ms

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.yodinfo.seed.dao: INFO
  file: ./logs/spring-boot-seed.log