server:
  port: 9001
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-seed
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    default-property-inclusion: non_empty
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  type-aliases-package: com.iakuil.seed.entity
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.iakuil.seed.common.db.AutoEnumTypeHandler

mapper:
  mappers: com.iakuil.seed.common.CrudMapper
  not-empty: true
  identity: mysql
  use-simple-type: false

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

knife4j:
  cors: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.iakuil.seed.dao: DEBUG
  file: ./logs/spring-boot-seed.log

jasypt:
  encryptor:
    password: Bda7bXaExAA
    property:
      prefix: "KaZ@["
      suffix: "]"