spring:
  shardingsphere:
    datasource:
      names:
        master
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://47.99.143.50:33060/harry?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: KaZ@[T9v+2rMY7Ug3rN7NgQzFOIxWTlHJ6ojT]
  redis:
    host: 106.12.75.75
    port: 6379
    password: KaZ@[ypgh62docYY/PPcZ0v16lGMDdKDTNSxq]
    lettuce:
      pool:
        max-active: 8
        max-wait: 5000ms
        max-idle: 8
        min-idle: 0
    timeout: 10000ms

scheduling:
  enabled: false
