server:
  port: 8765
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true

spring:
  application:
    name: spring-seed
  profiles.active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    default-property-inclusion: non_empty
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.143.50:33060/test?characterEncoding=utf8
    username: root
    password: Yod@[YWOni6tyv0hHGQtCUoEKAypUoxNCu8OB]
  redis:
    host: redis.iakuil.com
    port: 6379
    password: Yod@[ypgh62docYY/PPcZ0v16lGMDdKDTNSxq]

mybatis:
  type-aliases-package: com.yodinfo.seed.domain
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    default-enum-type-handler: com.yodinfo.seed.util.AutoEnumTypeHandler

mapper:
  mappers: com.yodinfo.seed.common.BasicMapper
  not-empty: true
  identity: mysql
  use-simple-type: false

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.yodinfo.seed.dao: DEBUG
    com.p6spy.engine.spy.appender: INFO
  file: ./logs/spring-boot-seed.log

jasypt:
  encryptor:
    password: Bda7bXaExAA
    property:
      prefix: "Yod@["
      suffix: "]"

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://47.99.143.50:33060/test?characterEncoding=utf8
    username: root
    password: Yod@[YWOni6tyv0hHGQtCUoEKAypUoxNCu8OB]

---
spring:
  profiles: prod

logging:
  level:
    root: WARN