spring:
  shardingsphere:
    datasource:
      names:
        master,slave1,slave2
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://106.12.99.31:3306/iakuil?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: KaZ@[jXy3aYdJbFf8rkj4HWUG+FZ41gh6/WmN]
      slave1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://119.45.239.30:3306/iakuil?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: KaZ@[jXy3aYdJbFf8rkj4HWUG+FZ41gh6/WmN]
      slave2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://81.71.3.113:3306/iakuil?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: KaZ@[jXy3aYdJbFf8rkj4HWUG+FZ41gh6/WmN]
    masterslave:
      load-balance-algorithm-type: round_robin
      name: dataSource
      master-data-source-name: master
      slave-data-source-names: slave1,slave2
    props:
      sql:
        show: true
  redis:
    password: KaZ@[w1APlX+Ao7TNZCdV1/1iNILSyfoDVelr]
    timeout: 10000ms
    cluster:
      nodes:
        - 106.12.99.31:7001
        - 106.12.99.31:7002
        - 119.45.239.30:7003
        - 119.45.239.30:7004
        - 81.71.3.113:7005
        - 81.71.3.113:7006
      max-redirects: 3
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 5
        max-wait: 5000ms

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.iakuil.bf.dao: DEBUG
  file: ./logs/base-framework.log

bf:
  scheduling:
    enabled: true

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
      limit: 10000
      defaultExpireInMillis: 10000