spring:
  shardingsphere:
    datasource:
      names:
        master
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://47.99.143.50:33060/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: KaZ@[T9v+2rMY7Ug3rN7NgQzFOIxWTlHJ6ojT]
  redis:
    host: 106.12.75.75
    port: 6379
    password: KaZ@[ypgh62docYY/PPcZ0v16lGMDdKDTNSxq]
    lettuce:
      pool:
        max-active: 8
        max-wait: 5000ms
        max-idle: 8
        min-idle: 0
    timeout: 10000ms
  cloud:
    sentinel:
      transport:
        dashboard: localhost:10111
      eager: false

bf:
  scheduling:
    enabled: false

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
      limit: 10000
      defaultExpireInMillis: 10000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      uri:
        - redis://I_%40_redis2019@106.12.75.75:6379/1?timeout=5s
      expireAfterWriteInMillis: 5000