server:
  port: 10240
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: base-framework
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    default-property-inclusion: non_empty
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    schema: classpath:sql/schema-*.sql
    data: classpath:sql/data-*.sql
    initialization-mode: never
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc
  boot:
    admin:
      client:
        url: http://localhost:10110
        instance:
          name: 基础框架
          prefer-ip: true
        register-once: false

mybatis:
  type-aliases-package: com.iakuil.dao.entity
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.iakuil.bf.common.db.AutoEnumTypeHandler
  type-handlers-package: com.iakuil.bf.dao.json

mapper:
  mappers: com.iakuil.bf.common.db.CrudMapper
  not-empty: true
  identity: mysql
  use-simple-type: false

pagehelper:
  helperDialect: mysql
  reasonable: true
  params: count=countSql

management:
  health:
    defaults:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      enabled: true

kaptcha:
  height: 50
  width: 200
  content:
    length: 4
    source: abcdefghjklmnopqrstuvwxyz23456789
    space: 2
  font:
    color: black
    name: Arial
    size: 40
  background-color:
    from: lightGray
    to: white
  border:
    enabled: true
    color: black
    thickness: 1

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.iakuil.bf.dao: DEBUG
  file: ./logs/base-framework.log

jasypt:
  encryptor:
    password: Bda7bXaExAA
    property:
      prefix: "KaZ@["
      suffix: "]"